"""
Common Model Utilities
=======================
Shared types, enums, and base classes used across all domain models.

This module solves three cross-cutting problems:

1. **ObjectId handling** — MongoDB uses ``bson.ObjectId`` as its primary key
   type, but Pydantic v2 and JSON don't natively support it. We define a
   custom ``PyObjectId`` annotation that validates ObjectId strings on input,
   serialises them as strings in JSON responses, and passes through real
   ObjectIds when talking to MongoDB.

2. **Enums** — Centralised string enums for fields like ``gender``, ``status``,
   ``community``, ``role``, and ``suggestion_status``. Keeping them here avoids
   circular imports and gives the frontend a single reference for dropdown values.

3. **Base models** — ``MongoBaseModel`` adds ``id``, ``created_at``, and
   ``updated_at`` fields that every MongoDB document shares, plus JSON
   serialisation config for ObjectIds.

Usage::

    from app.models.common import PyObjectId, Gender, MongoBaseModel

    class CandidateInDB(MongoBaseModel):
        first_name: str
        gender: Gender
"""

from datetime import datetime
from enum import Enum
from typing import Annotated, Any

from bson import ObjectId
from pydantic import BaseModel, BeforeValidator, ConfigDict, Field


# =============================================================================
# ObjectId Handling
# =============================================================================

def _validate_object_id(value: Any) -> ObjectId:
    """
    Validate that a value is a valid MongoDB ObjectId.

    Accepts:
        - A ``bson.ObjectId`` instance (passthrough).
        - A 24-character hex string (converted to ObjectId).

    Args:
        value: The raw value to validate.

    Returns:
        A ``bson.ObjectId`` instance.

    Raises:
        ValueError: If the value is not a valid ObjectId or hex string.
    """
    if isinstance(value, ObjectId):
        return value
    if isinstance(value, str) and ObjectId.is_valid(value):
        return ObjectId(value)
    raise ValueError(f"Invalid ObjectId: {value}")


# Annotated type that Pydantic uses for validation and serialisation.
# - BeforeValidator runs _validate_object_id before Pydantic's own checks.
# - In JSON output, ObjectIds are serialised as plain strings (24-char hex).
PyObjectId = Annotated[ObjectId, BeforeValidator(_validate_object_id)]


# =============================================================================
# Enums
# =============================================================================

class Gender(str, Enum):
    """
    Biological gender of a candidate.

    Used for filtering: matching always searches the opposite gender.
    """
    MALE = "male"
    FEMALE = "female"


class CandidateStatus(str, Enum):
    """
    Lifecycle status of a candidate in the system.

    - ``active``: available for matching.
    - ``paused``: temporarily unavailable (e.g. dating someone).
    - ``engaged``: match was successful — no longer available.
    - ``married``: final state after engagement.
    - ``archived``: soft-deleted by a matchmaker.
    """
    ACTIVE = "active"
    PAUSED = "paused"
    ENGAGED = "engaged"
    MARRIED = "married"
    ARCHIVED = "archived"


class Community(str, Enum):
    """
    Religious community / stream of the candidate.

    Used as a hard filter in matching — v1 matches within the same community.
    This list covers the main orthodox streams; can be extended later.
    """
    LITVISH = "litvish"
    CHASSIDISH = "chassidish"
    DATI_LEUMI = "dati-leumi"
    SEPHARDI = "sephardi"
    MIXED = "mixed"


class MatchmakerRole(str, Enum):
    """
    Role of a matchmaker user in the system.

    - ``admin``: can manage other matchmakers, view audit logs, force re-embed.
    - ``matchmaker``: standard user — can manage candidates and run matches.
    """
    ADMIN = "admin"
    MATCHMAKER = "matchmaker"


class SuggestionStatus(str, Enum):
    """
    Lifecycle status of a match suggestion.

    Follows the real-world shidduch process:
    proposed → reviewing → contacted → met → declined/engaged.
    """
    PROPOSED = "proposed"
    REVIEWING = "reviewing"
    CONTACTED = "contacted"
    MET = "met"
    DECLINED = "declined"
    ENGAGED = "engaged"


class SuggestionSource(str, Enum):
    """
    How a suggestion was created.

    - ``ai``: generated by the matching pipeline (vector search + GPT rerank).
    - ``manual``: manually created by a matchmaker based on their own judgment.
    """
    AI = "ai"
    MANUAL = "manual"


class PersonalStatus(str, Enum):
    """Candidate's personal/civil status."""
    SINGLE = "single"
    DIVORCED = "divorced"
    WIDOWED = "widowed"
    OTHER = "other"


class PhoneType(str, Enum):
    """Type of mobile phone the candidate uses."""
    SMARTPHONE = "smartphone"
    KOSHER = "kosher"
    BASIC = "basic"


class ParentsMaritalStatus(str, Enum):
    """Marital status of the candidate's parents."""
    MARRIED = "married"
    DIVORCED = "divorced"
    WIDOWED = "widowed"
    SEPARATED = "separated"


# =============================================================================
# Base Models
# =============================================================================

class MongoBaseModel(BaseModel):
    """
    Base model for all documents stored in MongoDB.

    Provides three universal fields:
        - ``id``: maps to MongoDB's ``_id`` field (aliased).
        - ``created_at``: timestamp when the document was first inserted.
        - ``updated_at``: timestamp of the last modification.

    Configuration:
        - ``populate_by_name=True``: allows using either ``id`` or ``_id``
          when constructing from a Mongo document.
        - ``arbitrary_types_allowed=True``: permits ``bson.ObjectId`` in fields.
        - ``json_encoders``: serialises ObjectId as string in JSON responses.
    """

    model_config = ConfigDict(
        populate_by_name=True,
        arbitrary_types_allowed=True,
        json_encoders={ObjectId: str},
    )

    id: PyObjectId = Field(default_factory=ObjectId, alias="_id")
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)


class PaginatedResponse(BaseModel):
    """
    Generic wrapper for paginated list responses.

    Used by all list endpoints (GET /candidates, GET /suggestions, etc.)
    to return items alongside pagination metadata.

    Attributes:
        items: The list of results for the current page.
        total: Total number of matching documents across all pages.
        page: Current page number (1-based).
        page_size: Number of items per page.
        total_pages: Total number of pages (computed from total / page_size).
    """

    items: list[Any]
    total: int
    page: int
    page_size: int
    total_pages: int
